FilmSite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('collection.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collection/urls.py
from django.urls import path

from . import views

app_name = 'collection'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:shelf_id>/add_film/', views.add_film, name = 'add_film'),
    path('<int:shelf_id>/<int:movie_id>/delete_film/', views.delete_film, name = 'delete_film'),
    path('<int:shelf_id>/<int:pk>/', views.UpdateView.as_view(), name='update'),
    path('<int:shelf_id>/<int:movie_id>/edit_film/', views.edit_film, name = 'edit_film'),
    path('<int:user_id>/add_shelf/', views.add_shelf, name = 'add_shelf'),
    path('<int:shelf_id>/delete_shelf/', views.delete_shelf, name = 'delete_shelf'),
    path('register/', views.RegisterView.as_view(), name ='register'),
    path('create_user/', views.create_user, name ='create_user'),
]

collection/models.py
from django.db import models
from django.conf import settings

class Shelf(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, default = 1)
    shelf_name = models.CharField(max_length = 100)
    shelf_size = models.PositiveIntegerField(default = 0)
    def __str__(self):
        return self.shelf_name

class Movie(models.Model):
    shelf = models.ForeignKey(Shelf, on_delete = models.CASCADE)
    movie_name = models.CharField(max_length = 100)
    movie_genre = models.CharField(max_length = 100)
    release_year = models.PositiveIntegerField(default = 2018)
    movie_summary = models.TextField()
    movie_poster = models.TextField(null = True)
    def __str__(self):
        return self.movie_name
    

collection/views.py
from django.http import HttpResponseRedirect, HttpRequest
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User, Permission
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.utils.decorators import method_decorator
from django.core.files import File
from PIL import Image
from .models import Shelf, Movie
import requests

class IndexView(generic.ListView):
    template_name='collection/index.html'
    context_object_name='shelf_list'
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(IndexView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        """Return 10 shelves in alphabetical order"""
        return Shelf.objects.order_by('shelf_name')[:10]

class DetailView(generic.DetailView):
    model = Shelf
    template_name='collection/detail.html'

class UpdateView(generic.UpdateView):
    model = Movie
    template_name='collection/update.html'
    fields = ['movie_name', 'release_year', 'movie_genre', 'movie_summary']

class RegisterView(generic.TemplateView):
    template_name = 'registration/register.html'

def create_user(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    email = request.POST.get('email')

    User.objects.create_user(username,email ,password)

    user = authenticate(username = username, password = password)
    login(request, user)

    return HttpResponseRedirect(reverse('collection:index'))

def add_shelf(request, user_id):
    current_user = get_object_or_404(User, id=user_id)
    new_shelf = Shelf()

    new_shelf.user = current_user
    new_shelf.shelf_name = request.POST['name']

    new_shelf.save()

    return HttpResponseRedirect(reverse('collection:index'))

def delete_shelf(request, shelf_id):
    to_delete = get_object_or_404(Shelf, id=shelf_id)

    to_delete.delete()

    return HttpResponseRedirect(reverse('collection:index'))

def add_film(request, shelf_id):
    current_shelf = get_object_or_404(Shelf, id=shelf_id)
    new_film = Movie()

    new_film.movie_name = request.POST['title']
    new_film.movie_genre = request.POST['genre']
    new_film.release_year = request.POST['year']
    new_film.movie_summary = request.POST['summary']
    new_film.movie_poster = request.POST['poster']
    new_film.shelf = current_shelf

    if len(new_film.release_year) > 4:
        new_film.release_year = int(str(new_film.release_year)[0:4])

    new_film.save()

    current_shelf.shelf_size += 1
    current_shelf.save()

    return HttpResponseRedirect(reverse('collection:detail', args=(shelf_id,)))

def delete_film(request, shelf_id, movie_id):
    to_delete = get_object_or_404(Movie, id=movie_id)
    current_shelf = get_object_or_404(Shelf, id=shelf_id)

    to_delete.delete()

    current_shelf.shelf_size -= 1
    current_shelf.save()

    return HttpResponseRedirect(reverse('collection:detail', args=(shelf_id,)))

def edit_film(request, shelf_id, movie_id):
    changed_film = get_object_or_404(Movie, id= movie_id)
    current_shelf = get_object_or_404(Shelf, id = shelf_id)
    
    changed_film.movie_name = request.POST['title']
    changed_film.movie_genre = request.POST['genre']
    changed_film.release_year = request.POST['year']
    changed_film.movie_summary = request.POST['summary']

    changed_film.save()
    current_shelf.save()

    return HttpResponseRedirect(reverse('collection:detail', args=(shelf_id,)))

collection/templates/base.html
{% load static %}
<html>

<head>
    <title>Film Collection</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato|Montserrat" rel="stylesheet"> 
    <link rel="stylesheet" type="text/css" href="{% static 'collection/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    {% block head %}
    {% endblock %}
</head>

<body>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <!--bootstrap extension-->
    <script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>

    {% if user.is_authenticated %}

        <nav class="navbar navbar-default navbar-expand-lg">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">Film Collection</a>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <li> Hello, {{user.get_username}} &nbsp; &nbsp;</li>
                    <li class="active"><a href="{% url 'logout'%}?next=/">Logout</a></li>
                </ul>
            </div>
        </nav>
    {% endif %}
    
    {% block body %}
    {% endblock %}
    <hr>
</body>

</html>

collection/templates/collection/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body %}
<div class="container color-navy">
    <div class="title">
        <p> {{ shelf.shelf_name }} </p>
    </div>
    <table class="table body-font color-navy">
        <thead>
            <th>Title</th>
            <th>Genre</th>
            <th>Year</th>
            <th></th>
            <th></th>
        </thead>
        <tbody>
            {% for movie in shelf.movie_set.all %}
            <tr>
                <td for="movie{{ forloop.counter }}">{{ movie.movie_name }}</td>
                <td for="movie{{ forloop.counter }}">{{ movie.movie_genre }}</td>
                <td for="movie{{ forloop.counter }}">{{ movie.release_year }}</td>
                <td title="Edit"><a href="{% url 'collection:update' shelf.id movie.id %}"class ="button-edit"><span class="fa fa-edit"></span></a></td>
                <td title="Delete"><a href="{% url 'collection:delete_film' shelf.id movie.id%}"class ="button-trash"><span class="fa fa-trash"></span></a></td>
            </tr>
            <tr class="summary">
                <td colspan=5>
                    <div class="hiddenSummary" for="movie{{ forloop.counter}}">
                         <p class="summary-content">{{ movie.movie_summary }}
                         </p>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class ="container">
        <input id = "search-text" class="form-control form-spacing" type="text" placeholder="Search">
    </div>
    
    <form class="row" action="{% url 'collection:add_film' shelf.id %}" method="post">
        {% csrf_token %}
        <div class="col-sm-4 form-group">
            <img src = "{% static 'imgs/placeholder_poster.png' %}" id ="movie-poster"></img>
        </div>
        <input id = "form-poster-url" hidden name ="poster">
        <div class="col-sm-6 form-group">
            <input required id = "form-title" class="form-control form-spacing" type="text" name="title" placeholder="Title">
            <input required id = "form-genre" class="form-control form-spacing" type="text" name="genre" placeholder="Genre">
            <input required data-placeholder="" id = "form-year" data-mask="9999" class="form-control form-spacing" type="text" min="0000" max="2050" name="year"
                placeholder="Year">
            <textarea rows="4" id = "form-plot" class="form-control form-spacing" type="text" name="summary" placeholder="Enter a summary"></textarea>
        </div>
        <div class="col-sm-2 form-group">
            <button class="button-yin form-spacing" type="submit"> ADD FILM </button>
            <button id ="reset-button" class="button-yang form-spacing" type="reset"> CLEAR </button>
            <a class="button-yang form-spacing" href="{% url 'collection:index' %}">BACK TO INDEX</a>
        </div>
    </form>
</div>

<script>
    $(document).ready(function () {
        var default_img = $('#movie-poster').attr('src');
        $('.table tr').click(function () {
            var s = $(this).next('.summary');
            s = s.children().children('.hiddenSummary');
            s.slideToggle();
        });
        $('#reset-button').click(function(){
            $('#form-plot').text("");
            $('#movie-poster').attr('src',default_img);

            $('#search-text').val("");
        });
        $('#search-text').keyup(delay(function () {
            if ($('#search-text').val().trim() == ''){
                $('#reset-button').click();
                return;
            }
            var title = $('#search-text').val().replace(' ','_');
            var url = 'https://www.omdbapi.com/?t='+title+'&apikey=db0e2d8f'; // plot parameter can be added/removed for more/less detail
            $.getJSON(url, function(data){
                if (data[Response] != 'False'){
                    $('#form-title').val(data["Title"]);
                    $('#form-genre').val(data["Genre"]);
                    $('#form-year').val(data["Year"]);
                    $('#form-plot').text(data["Plot"]);
                    if (data["Poster"] != "N/A"){
                        $('#form-poster-url').val(data["Poster"]);
                        $('#movie-poster').attr('src',data["Poster"]);
                    }
                }
            });            
        }, 500));
    });

    function delay(fn, ms) {
        let timer = 0;
        return function(...args) {
            clearTimeout(timer);
            timer = setTimeout(fn.bind(this, ...args), ms || 0);
        };
    }
</script>
{% endblock %}

collection/templates/collection/index.html
{% extends 'base.html' %}

{% block body %}
<div class="container color-navy">
    <div class="title">
        <p> {{user.get_username.upper}}'S FILM COLLECTION</p>
    </div>
    <div class="shelf_list">
        {% if user.shelf_set.count > 0 %}
        <table class="table body-font color-navy">
            <thead>
                <th>Shelf Name</th>
                <th>Number of Movies</th>
                <th></th>
            </thead>
            <tbody>
                {% for shelf in user.shelf_set.all %}
                <tr href="{% url 'collection:detail' shelf.id %}">
                    <td>{{ shelf.shelf_name }}</td>
                    <td>{{ shelf.shelf_size }} </td>
                    <td title="Delete" ><a href="{% url 'collection:delete_shelf' shelf.id %}"class ="button-trash"><span class="fa fa-trash"></span></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>You haven't made a shelf yet.</p>
        {% endif %}
        <form class="row" action="{% url 'collection:add_shelf' user.id %}" method="post">
            {% csrf_token %}
            <div class="col-sm-5 form-group">
                <input required class="form-control form-spacing" type="text" name="name" placeholder="Shelf Name">
            </div>
            <div class="col-sm-2 form-group">
                <button class="button-yin form-spacing" type="submit"> ADD SHELF </button>
            </div>
        </form>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.table tr').click(function () {
            var link = $(this).attr('href');
            if (link) {
                location.href = link;
            }
        });
    });
</script>
{% endblock %}

collection/templates/collection/update.html
{% extends 'base.html' %}

{% load staticfiles %}
{% block body %}
<div class="container color-navy">
    <div class="title">
        <p> {{ movie.movie_name }} </p>
    </div>
    <form class="row" action="{% url 'collection:edit_film' movie.shelf.id movie.id %}" method="post">
        {% csrf_token %}
        <div class="col-sm-4 form-group">
            {% if movie.movie_poster %}
                <img src = "{{movie.movie_poster}}" name = "poster" id ="movie-poster"></img>
            {% else %}
                <img src = "{% static 'imgs/placeholder_poster.png' %}" name = "poster" id ="movie-poster"></img>
            {% endif %}
        </div>
        <div class="col-sm-6 form-group">
            <input required class="form-control form-spacing" type="text" name="title" value="{{movie.movie_name}}">
            <input required class="form-control form-spacing" type="text" name="genre" value="{{movie.movie_genre}}">
            <input required data-placeholder="" data-mask="9999" class="form-control form-spacing" type="text" min="0000" max="2050"
                name="year" value="{{movie.release_year}}">
            <textarea rows="4" class="form-control form-spacing" type="text" name="summary">{{movie.movie_summary}}</textarea>
        </div>
        <div class="col-sm-2 form-group">
            <button class="button-yin form-spacing" type="submit"> SAVE </button>
            <button class="button-yang form-spacing" type="reset"> CLEAR </button>
        </div>
    </form>
    <a class="button-yang" href="{% url 'collection:detail' movie.shelf.id %}">CANCEL</a>
</div>

<script>

</script>
{% endblock %}